language: php
php:
- 7.4
script: "./php_build.sh"
before_install:
- chmod +x ./php_build.sh
branches:
  only:
  - feature/SINF-186_create_skeleton
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.london.cloud.service.gov.uk
  organization: ccs-scale-cat
  space: sandbox
  on:
    branch: feature/SINF-186_create_skeleton
env:
  global:
  - secure: Dl6ua5mX+hcfCGMfC3AfY0y6WZ63a2ZG+pemRmve22UUiAIw+p7FCyUkQOuLh3XWT172/jOJtGYN+5hQgTOdqVhxR750qWTo2vqwPa2DQR8tPFzrtlPB91ZQKpXWK6f4VoBkl8o8Vl3vBgenrR8UzgNodrBXDdcQ9Ud7w1tjixZM0sw4aRBD3I3TDpb6TUbdD8fWFP718+Nq5YWNLhE4zbm4zkw38C+i7Wp+NpmnkwFY3iNNAqRQu55LfoqB7zgwNgbKYNzaKutG3nBT/U9u4h2zItfSVWrgIRqdJ+IVolxrkCBnsHg28atewsVLtLKWzeviwr26PEuW1fiXqg7xkrpT5lju9+OaWRYhr/n/RHTlI5VhvOw+HOljHXRrk3H5zhEbrDDqKo2z6BEP1/Kc3ka4CWGqOqoPWYn4M5wI7/wb2zxBCva8TaiACe5ugIQ2kMOHxaA1Sro4/lTwYGtI1+NLzvyKRLSv6Qg7F8SKoiRDvq1DXpBLa32R6hHQk5spuy5D3t/imX2slCw4ACHuW27lXovxhAOfT0Of1ugwPqkpTvNHS41+r9hewiSpozDVK+S91we5/hLoerzwT4p1B0nIiBPrKK/6I6BRo2kJXqyhvHPaooz7phKtjBgJt3qeky8ZN8D3Qou7GC4bIFgdcuk2l3esac3BcXI3a08p5YY=
  - secure: SDmoXY+vt084xHqWO4cXdhecjekq5uPKxijldHf5n/5X4Nyl7ajGi9sBzna59wHrQxQfO/V8CSDmbDF8iSw3f0i5jEGWpis99jwS1uSAq3NGbUsJUynZDt+QmFV1G2xILF3rWEhQlWBf4WI4MVA0lq9XMBwGev6BGnRi+FRuJQvNwcPmrlmMng0j8zsRK6AAFElljGIFxAH9+yd9JAbdicdg6S5YIEQCRfFvP7pqZ+xERrjRqxnl7Dwze6l13YsgYvk1Efz2b038DdiHqXrhTQjwiq2gptjnhvi5p2gODDUGC1HlJAbQEsmKwOttvibQVDyDf3B8YaO+XGqp/nXGBmaqXjsBGYHNiKY5ovygzz7W3nYpqxpLS2xPvIoj85P+bSFcv0BdgTbcxAQn4tA26dcX6bXjG8tUIgwbcbi1cebqBJDtpHOXrxgJJ1TCXQB0w5MmR7ATPninYIRDq6dKo/yyvxKX+wWv46Rwh2t6JCVCoWBb7Mh90dNtOK2h03hQUsISBD+A4tZ1Wm1mvfj3dvazNqwHKNKR/p2ipXn9sY24XB3JfB/Co8o0WkByxXDVZIyOw/gm1ktqeMxyFWYJIwFgrIYTa8g55AaNIgFuk/03yiN/Wx0FDy3wxvV3wZCQDulFwn7T4+GZaLcNaHDeDvhhpEltsYKijiyuLynZUKw=
