language: shell
os: linux
dist: xenial

branches:
  only:
    - "/^(feature|bugfix)\\/(SCC|SCAT)-[0-9]+.*$/"
    - "/^(release)\\/.*$/"
    - develop
    - main

# Install dependencies
before_install:
  - sudo rm -Rf terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo rm -Rf terraform
  - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
  - unzip terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TF_VERSION"_linux_amd64.zip

deploy:
  # SBX - modify CF_ENVIRONMENT as required
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=sbx1 bash ./deploy.sh
    on:
      all_branches: true
      condition: "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^(feature|bugfix)\\/(SCC|SCAT)-[0-9]+.*$"

  # DEVELOP
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=dev bash ./deploy.sh
    on:
      branch: develop

  # INT (SIT)
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=int bash ./deploy.sh
    on:
      branch: release/int

  # NFT
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=nft bash ./deploy.sh
    on:
      branch: release/nft

  # UAT
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=uat bash ./deploy.sh
    on:
      branch: release/uat

  # PRE-PRD
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=pre bash ./deploy.sh
    on:
      branch: release/pre

# WARNING! Do NOT use the --add flag of travis cli encrypt - it removes all formatting and comments
env:
  global:
    # ACCESS_KEY_ID
    - secure: "IcBhUWf52G8pGR1bhtFgh6SBBPkI8LsElVUoizLke44Sw+nRvgYa9MAvgDMlcydx/+rkONdK9QMA/FtUAuGX0Fe8g1dya6D8ysur6ZO8ayArjzz0L57LAmWNjK5KD+JJBsIad0wko30d/MSJ12Tg+0zSt+lpQsW6NP6jLiTMZWHmNLOZ4eRGKq14Tru6rdKgjeIh0+wE/8XGoGH/JJ3mO1364M3GuUsKeoNIMv1RLdKevcCoj8AmmjgJFx6SOrILnG+Aa0bWu7mQS97KhizkiOiKx1pR5ASZs1SdmcUTfnxRZLyY/4pU8e86p0TGrRRaA8fm0eniMmQn+5JHZdJrl7iH4QMETWcrQSbZtoNstzn8mJ16NN7MP/vTOOUeVN1V+uOV+WgeXFc7ZOJ1iew/KvBYRDZUi47w3u0qiYCoq3cA6xgs62YJQSk0A8QjJ4us81ppN1rwDSiRcKPVeOFNwkrd+zBPPF8cXmmptp8q8OfEIbMXWPQmnaJpqV6HKjfRHRubg/IKCW7Nq3SyrPwaG+J6j72blbpeq8tffiTpT1anYJxbraGZUlU8+0DOH5dESP/ApqJYLR2xH1n/PtqKAu3wOAzZOX10bxX0pckuwW2NjhSoRKHxCAFgW0MvXJK1Mqw7PU8kC0ki+qMlOBuCsUOYmjnd9kje+Lq6uB9FheI="
    # SECRET_ACCESS_KEY
    - secure: "lX2miuww+f3c9+5414EX5sPAwa26PXWQhRml5FyU9tk3zv+c8fK/jEznvoX//yBOJ25rY6NPp0PCz3A3yv/OLktt5bwU6AQ8nNHimlDKE/rsK0JacsYLlPMnvJmVwmxSupRkGhoCBFyMhIem0HzZJcQ0b67Q1Gn/bxAQXC7FMzsvKu6L5Ivo2QpWHxBgsY0wTQNL5nkD4ySPQk155KXiaTBs3yzKvL2vg0xY9syLGlTnxcb+XgcH+xTiwtLFCeEGo6oKSrd0amJYF6TNOKbfIl0V8aT+q0pUGJyCuTxFeUK1aj3LGXQ+cn3xT4I2Ut5myP7/0NsYCUf24gvV4rjGvtj0E+i0fI47r2xZ/hLBNysaTVcR/DiotHKLEtnjZm/2BtOvo0vewTmBQbe/oq5vdlyJLWldbesZMx2Fq0oGp7slhPBrYH9H1rnh+a9EdVTBCAO0Dv9sQePW9V3w1VGkYVW9QiTf5P8lDA8cDkrlv1+HlMeOfArbcokOq9lxtkhUSsZYyx1wphnIdUt1rmeePCsLVStiKrKMCbBP2mEx0keJMyFXR2EaA7tjyfZByMW5MWhfR0w2qd84PK7wR0K+LeMQ29Zj+i1rQBiwl1GZOuXongA4AketdcjxQI0xgk8RvMVXayquJaEfDrKmRTvUudfG499bWNkvOt34wGxEsj4="
    # S3_STATE_BUCKET_NAME
    - secure: "X+f8b9Q9BHnemZU6RA62w1grF9kTPBsk3CSTqCacmBw8nfcuUK6TC7Q3k0ZZVTgu5+jHHDPOJs6sjKrp0gvEypqa7niJQjyd2NuqoSxDTISZUBouikW83gxIyyW5PBwUhF+51xwmrRHI8moh6TEbf5lNvU+0td7DdK+LMkYpyr2xmO4jg5qGv6BjdCQdMrLxA6Yev32MkZVcDUcrLd5cWa7yqMypu9Y1KzgU5iUYnNsgJw1gTI4S6DIE6RoK7nEfdXFhtz0zMp5d65b9d1yhb7iwckkE4Y703y77tYsOer1uNj9DoiF8ZlpdL5fpfYcWxCXhJ0NW9GptYik4YWuAYVZu8M1N9S1Ft95zesAHa4tY5ntBm5ep0899npTxUhqbrvwpHt7iSuhln5CWVi+45TXSeX2WgHoNYlPl4d9imc64xxwMoHWriDTkktMxjYQXwRc67AOlHj0JIlTr9J4nJOZ4ZxYzaoICsaCvQPzkZ96AKfEZrthejo3b+qLOt+3aEaywVs8gloFv+iPVfzU2aeBFqOA20Blg96sanXhH6aS0pyAikX5MbzgcNfKfGrM15jvItBHnBh9SX98tIRPm0vn9kQln6ra+GGGNk2fDYXR5AXepGIMjN8mFpRgxbXytxWUxyuMKT3oW9bpOPzDlbSgdKMU9Le6RJIiuFh91vjw="
    # DDB_LOCK_TABLE_NAME
    - secure: "XD9sR+mXa/zk91KxwJx/oRrAo/MStUMiPIjUMGhWJO1g608ELPYDxqsNrEf+ovlXrDan5qVW0RH7ylU5CHnzpbXuqtukTltMfreXQcXKaIAY2UG6FAE8/TUNHrkF66uYdgUatSsAqJde+QBEzTIpDoRC0ZdRp5cgWgmRfrW6oswG1JbXMrQbsrcbTS3Ccey4NRTpHuIxpoGlIg4TvmR9+uSdH9sYa1yFRti0x7TBMZ4uB7ZiRh4V0w2TKnC4xrRY3ZlSXlepECGTiGvPMBFE5K/jr5DYr2hgcrfaQnviTq/e7Fobl2F9nTEZqSuyc1Dk2baQFEYxBhCyblfoJ5lolvzcjUpgxS+FjOAu3mtMvkqSXcY80OpvxBtzq1/BIfITepWEO8Y1FG9Ti6D1iJYfYj0omgCqFLmT0b6TC6ynVu7lK8OSTR+86baIArhnmi1BFpLG/RTBjE+IT5vJvJ/qtjZFUI6ziSne9dSHwycbMO18AtbYbQJa7DBfo9ZJ4MU3v7zKXcM0xejD9301JRar62+RONc7wrYRqBnfRLpzlFFnIn174k6rokKtzUeN0ShvbRw3OutFiBgRMB/9bZ/zR719jpmYt+E4h4iGT386jxRsEePzsMtmeYwJW55XM9sIjk0AiRycw+kKF3Y8MJyLD72HAc9mOkmwOD95Qm8FEfs="
    # CF_USERNAME
    - secure: "8vR6tbXwHAq7W1WQWaPAEw9kdfCOwiuTB0JKFy6F/I4K35mB9tglw5L6LslXY5V2BAIM3XHnukSzr0l5klk5B5FZwe4UIm+XCD3b+SmAL+zdEvwQEyTRrwpooz26MCXFpGMWU6+YLfGPvST/voM6svfV22VQlC+aGgORakTX9wHlArBo0FCs9/ks58Pks5Ih9s0tkK2D/2h5vStHeKoF/K+pnsO6bJl+xbCA81a5QIRwRGk/yFCYj6sviAdXSj/nNdG0CSQZih5bbwBwWgR+0tvm6k4/8bLUId4MCZk5D2Jk+fKhbskGSRIkZtr0hnbYmyLKsot0dW2XBp8V/5BDmMCHWiG+8RWyV2Xp4JBYPLlBjhHWZoGTAFtrb5pZtW9YgcyzNiF3xlk4y5jWDsD/iUv03RxZ2cISog4tpaETXWrRGSVq7gqmDz3JP0hCoP/LGdp7Eq2ABiffFpNS8CFWOy9Vxi7GztGX8EpX4NGZx9uSypkvnwyAMqrAxDZgO6J+9QGkwDqxp/iFEzcD/CEIXfjRrDM6BnC0cD1bWOQjKyn63Vp7FtnZ++X80u37Mt+FfV2KX1khUtiefaY7fu2hznjQYzxarGWp45kTE2QQaQO25HRpNtdfcDeG0FFxGdr32IovB+gTyFp5oL/xhvxQYc7n+30vmtT38pMmBwbnq9E="
    # CF_PASSWORD
    - secure: "8ARLNJkWSR3w0vnpdIA0YfemXOuO+8a9xvqdXLUYwPGsFzhfeqfsNcKN3ht/McKLAD+8HkrXC/2r3qqYpzi940eujzBcOpk4ufhXuFJokPyPx1Ncko2rCnBxq67mgKu6bWoja5H/FZxnhSPtFw/YjB5tzmeQI5YMWqMbVedjTVpUkkvGkm92QDTTfJXtUM6GtG0y+wFnSINLYpoS4FHNIWfmS2tVTDsORwHwn67btf54ekyQQeT4/kpyKd4c3zoC/0cDjGXVU/OQO6AktHHS3r9ZMftAOPUx/STB32RWoRtdcwAGvvvyXPBu+uADRUV6Puwe4ZCIDaB2EO4oIh4qtTIG5g8E5uyu9RdbOmLdVLYfmJ9Hxd5UwfuTA3rJ/QFWKVGPypK2Cv5pe8QKebRbkQLxrJkjiNMIs+wZQU6yr5FP3I/6QaGppCDSO3p3QFlUTIM+S9hgWSnhGvfm80jHLh+cE7KHqMr3Cea+E7ulijx45KZokV/ZZwN24YyNOWvJsKYJGc8Elqq+ET6cona3kdpA/S7DnLqaPI39nV/mRqtVum2boqcO7yoom0JhgvoqDMupBEMg0BSArJneKiVxkxN6jIOj+3CYwZtg5+f9Pn4O9S/qPOkL8rrU+j7Mf51poDwhtEBMR+w+YZpET6ZLK/iG7zygEqUY8KZYowNoeY4="
    - TF_VERSION=1.0.5
