language: php
php:
- 7.4
script: "./scripts/php_build.sh"
before_install:
- chmod +x ./scripts/php_build.sh
branches:
  only:
  - feature/SINF-186_create_skeleton
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.london.cloud.service.gov.uk
  organization: ccs-scale-cat
  space: sandbox
  on:
    branch: feature/SINF-186_create_skeleton
env:
  global:
  - secure: dYDUuace1z38OC8dwys9DJYz11orVHShMCWgMHFQRLFoTBjkCym+I9fj71gTmicNFTss8b2mldMbqmOfsEtjJzxxLH2mkUjGPSWc5orzDhlkE47g1YDzpfpebddEgufF2o6dkC69envye+tpjTZBrO884eeYv/pgDdtiXtBVs1GXyw++3bTh+fHcXxr+vHwDbGe3pNfiFX6oPsi9rSwBfNoDppvepUbo5rcx1hNKGuEYghKjh3LcKcCeMsG+V1F04O/TBElVNf7q3881HpGCl7ibN/kUW3Kjcl7fw4pWJPO6NsH34D58lgKB7c+WN2ZA6Bg1nehvPDym0l3CKq+y2R4S4V/mUK1w38TZrbyz+79gSrF8kkc/UDOqyPiFs6tSutm9j2Nvx02YiR+vepNLD+k252Z4iF1tTJs26rnhy4guaQZtbFZ7yTzrOp9EiLYXJK+nt55TAPzcCM0fGx8qLOCioCy8jtn1FHt4uGqf229Ht96j315tRXprsnoqjaq8gDDW+8ryYQ2u0d3dCYAzAKXisftCMTZopk/1tSjXWr7Jnh8NFz3aS7YSZK4pnYa6HTNPS94I39WVRpiyHsXJUTXJFEsSC/YkitgFQcGPrUhFzotxw/yRCTuzUbNV1Lh2w6A7tWjdyElEfvN29wMKwlJFWqowie+M1GPtzdpkaYo=
  - secure: iphK5SNzOj3KPyauEcsYUfwFg0p9zmhVUpF6piFRZEeAYRrQSz6/Zr+heVr2inW1ISqV/p8VHmamWjnGyzheWCbauLnQHm6AvLtUU8/+fxPqQRkI957t6liP8wS5yxRFdjxOC8xZPPkrKb6hJ7dvC9YO9eN4zSPW7+r8hpE/Ugln2W5OSZI+LSdPKdbrcsNC7+x9hUPOs7X6d/dwiwGUVIIa3iOxTPdUSJmvdpc6VG5Vht/7b/Jw2lQHZNM0UuvJG6vXJ16uuHb2EhLWkfXPSaBHimYSOTonLl8sAbS6CFo3B5vEvTh0daH8S8eO/cm1FtcHIIkjZlZ0EtG7MDK1K5p+ZZAt9PVKuAU0S3V+ijjHlbyh9GW/9nIVHtSaSAMwkSTNPsOjS8Sg5ObHF4JRag4L5SwunTxIHbMytZP0j2LgIPsaIkl1xmYfX+2WozzVhd5JFBNV3x8V690Z/HXGIh1bK5kaUPTjNqwmmtHclLrOC5zG+0NsBr+wkxlsvipHKrH3GPH7eNT94XPjkUUdtceT2lp75tHZw0UUyW96nUlovDp6mjitIdmHGdtD2F9hgCcNUZXrLkdRuIkKopEjtVXYfecj8KWUhR/bB83IXsstv6gdzpE52BjlE9AY4k8/6iHee73AodISGxV0dCwoO6F9cl/AR+iikcs2gWg++ew=
