language: shell
os: linux
dist: xenial

branches:
  only:
    - "/^(feature|bugfix)\\/(SCC|SCAT)-[0-9]+.*$/"
    - "/^(release)\\/.*$/"
    - develop
    - main

# Install dependencies
before_install:
  - sudo rm -Rf terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo rm -Rf terraform
  - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
  - unzip terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TF_VERSION"_linux_amd64.zip

deploy:
  # SBX - modify CF_ENVIRONMENT as required
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=sbx1 bash ./deploy.sh
    on:
      all_branches: true
      condition: "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^(feature|bugfix)\\/(SCC|SCAT)-[0-9]+.*$"

  # DEVELOP
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=dev bash ./deploy.sh
    on:
      branch: develop

  # INT (SIT)
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=int bash ./deploy.sh
    on:
      branch: release/int

  # NFT
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=nft bash ./deploy.sh
    on:
      branch: release/nft

  # UAT
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=uat bash ./deploy.sh
    on:
      branch: release/uat

  # PRE-PRD
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=pre bash ./deploy.sh
    on:
      branch: release/pre

# WARNING! Do NOT use the --add flag of travis cli encrypt - it removes all formatting and comments 
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "8o+LN2cFq39KIlWoc3vyTRHyxyeZZNNFEsdQOV5hLq5qKw1LCZ/C+IGQMj/0rEhAPCgPskoqT6Ju+uWGT4Q63+sVBSxYnxpJAcp2HwCQpm8SdD+Mwi6i3dcwI+IfpfnEj5oDG9viIgwPYGhXoMKWHgZf5PwDmvae1uQ6HQBR7icMdKKH62zH2+B2cHDBC4QrryAf84WmbsSZGK6oqqmU3mAxifbFPP+HhtJrLyFScurkly/EaHisRSDgaHrL9AUhd850CiVIL5v9R3ZRDIUJBym9oL7KyE9H032b91jukY1ZZ/CYcgwSxh3vtZX80ekjEqOyonivsG5BWlgXsWCVlqQsHnxR0j0lvXC/7v80AODxSMV0z4UxQH4/EwYN+yRZG458s7Skucuzrb5045VuX2o1HQcuiuoxDcqxEWhxBiDe2rin7hSCwhWIxa7v5rYRLcRKqXmlnzyUZ1CUQU5oyxu/rDJH8K1rXJSHQQM1CIUVKQgxC1Pw50m1R/CaYzoiKBLGLRll63AIa3NJIaoREMER6arb7yVVtIFkgLVIsvwki3M8owphKUWY1TIJRxJpCNl4msKlqY52RRQ0+WNO3fg+mXcm824sRjUADNulBWDLu1cQnfeboHrf/X6TK45VE8rJCTupL7AQ7ilfVxYaPTt0PDO8VglpWIyIQmG/D+0="
    # AWS_SECRET_ACCESS_KEY
    - secure: "6IpTzhO9qviGgLYclG8S/k1o5ZLjcuHV+HzEL18XTwEUyDhLfPO/rtLVR/tisasWjlIEEYPBX0S+k6zujZWXyJ41nyEwLO1LTezPMojgjG1Fh3/8YapPDAFoycrXnu98sFVG0seytzh/YD0dlt2UitJQt3CU0VCZ02GoPbmACDiRxjilKsG8538qMBMqAD0iT85fj/BuuyUT7T0e6CiOaea2LJElSaOI0XUqbPT09/9YN3uGi815cvK/tPF4CYsg9BVJLX9HJHkqGy/GJl/z/RjFKNzvA2yuQ7xA0O43KP+YJvTQd21belzvb/GJhqBv7jJMG2dxTbj+MAuG2o5pak2lM3qsPM9B/xX2QptKRpW6hco6mhvTeNDRIj1Y3ofxQQvHqjWNIvE+ylLSGlIXoDNly+mjqP37DZGhKpRWBYjfAmzVrB16l8XPpA+po4qqSsI2uOgfyiR5aTEi0QxSs5aB6pJmBR2ZSlDbZQlFcVWR2x1JIMPDI5p245i8LdDS3BrX2+JS9KUQD079sgrFVnYr5H41fxEqL95S0eta2TH9/2n9jrehNLenlo6GmxCk0vvenuSVlvXsX79h8Bbx7XjFWUp2msuP9m5eDqVjIG493G117xE4kuWTgU7xYXEUbXgZVOxOjvVjMFbqq/x358SbYfhg8PSY1uNh0srF524="
    # S3_STATE_BUCKET_NAME
    - secure: "X+f8b9Q9BHnemZU6RA62w1grF9kTPBsk3CSTqCacmBw8nfcuUK6TC7Q3k0ZZVTgu5+jHHDPOJs6sjKrp0gvEypqa7niJQjyd2NuqoSxDTISZUBouikW83gxIyyW5PBwUhF+51xwmrRHI8moh6TEbf5lNvU+0td7DdK+LMkYpyr2xmO4jg5qGv6BjdCQdMrLxA6Yev32MkZVcDUcrLd5cWa7yqMypu9Y1KzgU5iUYnNsgJw1gTI4S6DIE6RoK7nEfdXFhtz0zMp5d65b9d1yhb7iwckkE4Y703y77tYsOer1uNj9DoiF8ZlpdL5fpfYcWxCXhJ0NW9GptYik4YWuAYVZu8M1N9S1Ft95zesAHa4tY5ntBm5ep0899npTxUhqbrvwpHt7iSuhln5CWVi+45TXSeX2WgHoNYlPl4d9imc64xxwMoHWriDTkktMxjYQXwRc67AOlHj0JIlTr9J4nJOZ4ZxYzaoICsaCvQPzkZ96AKfEZrthejo3b+qLOt+3aEaywVs8gloFv+iPVfzU2aeBFqOA20Blg96sanXhH6aS0pyAikX5MbzgcNfKfGrM15jvItBHnBh9SX98tIRPm0vn9kQln6ra+GGGNk2fDYXR5AXepGIMjN8mFpRgxbXytxWUxyuMKT3oW9bpOPzDlbSgdKMU9Le6RJIiuFh91vjw="
    # DDB_LOCK_TABLE_NAME
    - secure: "XD9sR+mXa/zk91KxwJx/oRrAo/MStUMiPIjUMGhWJO1g608ELPYDxqsNrEf+ovlXrDan5qVW0RH7ylU5CHnzpbXuqtukTltMfreXQcXKaIAY2UG6FAE8/TUNHrkF66uYdgUatSsAqJde+QBEzTIpDoRC0ZdRp5cgWgmRfrW6oswG1JbXMrQbsrcbTS3Ccey4NRTpHuIxpoGlIg4TvmR9+uSdH9sYa1yFRti0x7TBMZ4uB7ZiRh4V0w2TKnC4xrRY3ZlSXlepECGTiGvPMBFE5K/jr5DYr2hgcrfaQnviTq/e7Fobl2F9nTEZqSuyc1Dk2baQFEYxBhCyblfoJ5lolvzcjUpgxS+FjOAu3mtMvkqSXcY80OpvxBtzq1/BIfITepWEO8Y1FG9Ti6D1iJYfYj0omgCqFLmT0b6TC6ynVu7lK8OSTR+86baIArhnmi1BFpLG/RTBjE+IT5vJvJ/qtjZFUI6ziSne9dSHwycbMO18AtbYbQJa7DBfo9ZJ4MU3v7zKXcM0xejD9301JRar62+RONc7wrYRqBnfRLpzlFFnIn174k6rokKtzUeN0ShvbRw3OutFiBgRMB/9bZ/zR719jpmYt+E4h4iGT386jxRsEePzsMtmeYwJW55XM9sIjk0AiRycw+kKF3Y8MJyLD72HAc9mOkmwOD95Qm8FEfs="
    # CF_USERNAME
    - secure: "8vR6tbXwHAq7W1WQWaPAEw9kdfCOwiuTB0JKFy6F/I4K35mB9tglw5L6LslXY5V2BAIM3XHnukSzr0l5klk5B5FZwe4UIm+XCD3b+SmAL+zdEvwQEyTRrwpooz26MCXFpGMWU6+YLfGPvST/voM6svfV22VQlC+aGgORakTX9wHlArBo0FCs9/ks58Pks5Ih9s0tkK2D/2h5vStHeKoF/K+pnsO6bJl+xbCA81a5QIRwRGk/yFCYj6sviAdXSj/nNdG0CSQZih5bbwBwWgR+0tvm6k4/8bLUId4MCZk5D2Jk+fKhbskGSRIkZtr0hnbYmyLKsot0dW2XBp8V/5BDmMCHWiG+8RWyV2Xp4JBYPLlBjhHWZoGTAFtrb5pZtW9YgcyzNiF3xlk4y5jWDsD/iUv03RxZ2cISog4tpaETXWrRGSVq7gqmDz3JP0hCoP/LGdp7Eq2ABiffFpNS8CFWOy9Vxi7GztGX8EpX4NGZx9uSypkvnwyAMqrAxDZgO6J+9QGkwDqxp/iFEzcD/CEIXfjRrDM6BnC0cD1bWOQjKyn63Vp7FtnZ++X80u37Mt+FfV2KX1khUtiefaY7fu2hznjQYzxarGWp45kTE2QQaQO25HRpNtdfcDeG0FFxGdr32IovB+gTyFp5oL/xhvxQYc7n+30vmtT38pMmBwbnq9E="
    # CF_PASSWORD
    - secure: "8ARLNJkWSR3w0vnpdIA0YfemXOuO+8a9xvqdXLUYwPGsFzhfeqfsNcKN3ht/McKLAD+8HkrXC/2r3qqYpzi940eujzBcOpk4ufhXuFJokPyPx1Ncko2rCnBxq67mgKu6bWoja5H/FZxnhSPtFw/YjB5tzmeQI5YMWqMbVedjTVpUkkvGkm92QDTTfJXtUM6GtG0y+wFnSINLYpoS4FHNIWfmS2tVTDsORwHwn67btf54ekyQQeT4/kpyKd4c3zoC/0cDjGXVU/OQO6AktHHS3r9ZMftAOPUx/STB32RWoRtdcwAGvvvyXPBu+uADRUV6Puwe4ZCIDaB2EO4oIh4qtTIG5g8E5uyu9RdbOmLdVLYfmJ9Hxd5UwfuTA3rJ/QFWKVGPypK2Cv5pe8QKebRbkQLxrJkjiNMIs+wZQU6yr5FP3I/6QaGppCDSO3p3QFlUTIM+S9hgWSnhGvfm80jHLh+cE7KHqMr3Cea+E7ulijx45KZokV/ZZwN24YyNOWvJsKYJGc8Elqq+ET6cona3kdpA/S7DnLqaPI39nV/mRqtVum2boqcO7yoom0JhgvoqDMupBEMg0BSArJneKiVxkxN6jIOj+3CYwZtg5+f9Pn4O9S/qPOkL8rrU+j7Mf51poDwhtEBMR+w+YZpET6ZLK/iG7zygEqUY8KZYowNoeY4="
    - TF_VERSION=1.0.5
