language: php
php:
- 7.4
script: "./build.sh"
before_install:
- chmod +x build.sh
branches:
  only:
  - feature/SINF-186_create_skeleton
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.london.cloud.service.gov.uk
  organization: ccs-scale-cat
  space: sandbox
  on:
    branch: feature/SINF-186_create_skeleton
env:
  global:
  - secure: SRZ9/rOURqNwIE+x+r0sF2YPEvYvDXzpPbr+SCgO5nZ2WUSSTzUEh4hsrH18jWclPGkQFYcZhRjBWVWOf/SGCAZSFKz90gpwDFz4SeziAcoSbNq2XgEUGLCkPJQ0f13ihg0cSPTPmNYfiwVJ9MbNeM9r42D8Lgz/XXfZD+n/XC58qHEZIEGHvEgSDlZp3t2A8LPl4fy7aBoJqZNKikaCe87V9XqfjoyG0IqdIS3fiMT1442XEVG0fStHslQKZ/D/zs7pB6rjKkt0/pcHTra4NMwlfiTqoNxZAVF5CpbhfdM18lkY3fxpX2EO6Q/oLclXB5eU6w69C52PCKUOJyD2gVMf5qCXUCvde5gG7l/qn8HCKeMNhcDt2fSvY6cp+ZxMqs000vCS8RgOW4AGCYz3WYTtUeQvryKRXnJBAAlOLPgcbsei8eEY7zp5IEEODEE5tSJ+U3zd1be/KdVy8C+2aOjQc+vMJhPVjMRIyaTOovcLCxEWUaI+o0tZEsDWhYMlFKGmstm2YbL1b93spuwZktrrGPzh94I5PQnNhOfiiE5utIOXPyOT6w4CAb/d7Q1jCDqqdlVpIe6JokQjUdVV/iqp4gAXxAH/xBpFU6uuhZerVsT5h/HRhPBD7hrIF9/l02NktKTVrQqEIxErT/c8qIqHzYxD5FcUXuhIf/gnzKs=
  - secure: Z7IAqufwGgN7jwWJ/LC3q55SJOaF0Aw3+pXsgxQPFfZjGWXDge6IKe15yu/ULHUWZYk8ZNl2CRWZ4qzSo0yXtlyYbeBtwgevcpFLu1KPWdXxmwbateEkZ3f7jUERK/FW1tAXo0flcC5LnnWkKAFrfLTNblsDV7g9VaU2X852isnbSC71sJeMIO037P5wivOW5PdzmM26i6ZiW2fUbpop+Lgto3blj8ajfiqhVdHuwnooy6mulYeqI10pzdK5NfMd+pU2rpjq3D2fc+uajcuV/dxLxnBFcEQUcifwLNs9Ya7T68wG/lGitRkaXV+J3R7hI8gk/A4qPBvaagwoXaGqURRNrt+ZYn2iVUzwIVcwyBzwNQ4axm8BJXHb5WRxb+O/6llqxawP9LDK5zjBEWIzsX+rHo7LQ6fZgfPwaG4On0IOKAhlk7u/0ZC8E4y7mpc+qNVpTRYt4U9dppHkRCLv4AAbPZcrcy+IdA8eBV8FEY5g1ySaoH5Cdg1jktvirFZf8/Vbc66TIjvl/yOA1ufJexVCOAR4snj1z2QlRo+pRgrBYclQPXeHmtdQpLb6Wx2f9p1jOzrXuhQlGNmflROHW5OHRnHodIdcM+/HjY0FBcNAflK6dafvqYp1HlpyZ9lR7v2NEBeLSaXgk/9bbt6mHrmUsgmBj6aoYZc0MKL+Qu0=
