language: php
php:
- 7.4
script: "./scripts/php_build.sh"
before_install:
- chmod +x ./scripts/php_build.sh
- chmod +x ./scripts/cf-blue-green-deploy.sh
before_deploy:
- echo "Updating packages.."
- wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key |
  sudo apt-key add -
- echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
- sudo apt-get update
- echo "Installing cf cli"
- sudo apt-get install cf7-cli
- cf -v
- echo "Installing cf blue-green deploy plugin"
- cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
- cf install-plugin blue-green-deploy -r CF-Community -f
- echo "Plugin installed"
branches:
  only:
  - feature/blue_green_deployments
deploy:
  provider: script
  skip_cleanup: true
  script: "./scripts/cf-blue-green-deploy.sh ccs-scale-buyer-ui manifest-sandbox-blue-green.yml
    sandbox"
  on:
    branch: feature/blue_green_deployments
env:
  global:
  - secure: ExEpdwseioga4Sk7gahuUKZytETjxbQzIhnVihk1oXp9H/239uOsq7k9VGFWvgU35pNc0Csh5Lv9OoNHDuQ8rL9OvKpLboB1RKA15OIpaiRllQyPr8jWS7dZo09squg2eyxsiXH6h3sP/QkIkENGx08OT7mS3xrjQ9tGdzYuE6PBo9Cynkkwrtl0T1gHjcY3tPLhA3Qfw37i51Mjx9fxAes+5vtSwxh4yrXX7/tJMxnT4thvWIaeDFvyW+Es8P1kzg9MyCfo12urR9XNBGii3b9Zv5HViXL1JGlzoAJ6ZMMLCS4sBJYWqvFD4GTJ2H91RI5VA24Lxx9GPib3HyPsHh+z9kEjXIfqLnHivCc1Srw3HcZuSRpnrsJCS4TuzHeVCDDQLE5YEXwo2wcZM3P/gaer6Q/UfGrB/ecjeA3fozC0hsp/zrim6ib+znolGlFGj0z0PPfItEvSUR2K3Ib6grta5+MxGIuYo2wiVQtBkkAyyI6iXfdTlMq7zMcBe0Kru6FUUiHV6mSxPu5211hGmgxgmfvk1tBGX+Q/fhVONg4Z9kllZhPL1kFfP5jqK3S7r9Knk1m3srWnuNnYyykBrC/IJ9WPI6LLzlMFu/HMC8oBtWz5U2ycVLy549bO5bGfpkQoNYsK3ntYWp+HVvJJ3dRW/AhiOUU26vl1LQYy6/4=
  - secure: 3jLHeef51kTnUZb+J7JYPJlQN+BEzzXvWW3nN6TOLFWxRLpF4XiEZH34BVULasU80Coq4INYpg92mQawiqp/MgLXDw8wIJC/ZOO3UqeOXxNiE5l1Z8M6OyGRxNfEubp1e6EeEAgs02X07DOHdnfceE06GrRvQzdQ42pVNFN91Ccr28vPQLJWh18lJvb7ojEyCnxYLbm65uKKJ0ChKceBczYSjnpaQF3YkypOeVE2Zelg6t6VoJjqeen4vjkP3R0HUfrHaDjqNyZ1ojyFnJ9c46rhR5xv1hkpM0XyKo9XbyPolx8Xn20dhSr24uYdyzKEN536T9CU+w3xXTZbxqZOm6r/K0aRSUIiWtjrPjWoiU6gzGYrUiX+j6Z+vLeXM4ma13MIctKSv7DS1d2yn0NU+Kb05U2nUOfNvR8aiVzGkowcrvKZUfNJJfNGOBQ8r/3pavw62+ZUDbhCCAhu+iMa25OM2xlT9qKVWqBuE7TRlLR8tGDi9kAMYI0epbv+nefIyfkykPJ615/GTIicVV2abkBuU/91qSbCLM3TPRzq07sXrllODhjE/FOonDofVcMJUGQjCe4MXK71YqqqIEITwFFw474wkvDiNl3CYjvuvpLJ4aCV10cQEDLMgiU5nhM5BB9fLQEeK5IOCMXHTtm7qjkt0+N9aDQmJZXe85QWN14=
  - secure: NwOynPdQhA2drrLeozf5xSzAdevD0nF5d9CUwkvHcind8DSNJie/M77I4NON270XvsoQ8Aamb9PNvV+bLZb/bXLnM0bP64qLQ4FTGk1CIOtaLKqpUWtUFx4TCRRfpQTictLmy+FGL8sYMrDEd094J+amOx2sC8XZe2bAfsNGBwIslWIL+Nc/mduwSvEceb3CdtM/szOZjw2MVB3nj/mZ3tj4RDl6sWSI0C1aL29F6doRv0li07MmcXX3UW/7TYQTe2RK4GV52vbD+ptEOSMnT9LH+R1j0hEFMggoncsBKKZkDZTGRqZ3/vuHt7MSBrrUM6mzLO0B9hlKvGz0KwCcJek+XqqVdbzukd+U3TCwLnh9+kDPn6dO1Vc+P8+kQYcEJEBAuKWU4t77IRRNjjlqo8ViTPCsjEHqAtWeT/cV3OcvYJFz1Ab/sRal1obbNDA3oHrK12IwHWRXT3CqcraTY12ZIq/lsTgrMnsAgJGNXop6XT9GnW7C8ggK4bH5Zx13dCegi5/TUX6o4MO3YyxoUCCDbzc+Shndq7YDtZk902edvMHE8pe7aRHKKlJhngbizUlM05Rytzvo7C7yf8YIrjmZRudwXek6sm94rL8S60Nbojr2z+am0fIck1yTelRpc6caI6H/nSP77D5AoJ2i6VeYJpt/b0Jd4aeRvpb9JC8=
  - secure: O3oxcMTvUrPZ6t8boDX7WKhekybqXY2BHttc8VW7KCjAmXeWC02HN5uIug3NGQlS57Th7bq96gQdmOtqRCKiCvCkXCKwfsuFZx88R50N1u7yKn4vM9b64YCeE5vI2KtpxjTzOwXi/BnICIbkMQ+wAk8Aqss48AnlY/vDSnAKYiGuEsC+Ci1n10FsA0uUfXhWmI8B21cVeJ6u7p6VOrLUhhusZ5RgS0Yr6RAhw5BntLwqLevU+JYPrNy4zv6C4v0dOWEC2mlFDPHomhZ53DvgK4q9+3T+LIh3Z2ljyjmc9NF6ZDGPRTM0Wg3sQbJFf7L6WnmgpNpmYxatScsCOmdRlSdXkfWHbrwuz2Ota1bA2sqZMF3idOKFwT1IbCm3ogpdNEVV/jdjAM1E5+oqnpShbhTq9L92cPAswcqwenWbR3JRtEyMfaMyBUZte3GdYvWflCdoaKq6Cn+iM3PRuX63hTNdWThs9fNWFzDAPBz8oLu6/bKS1TLZxTZjdG6pXfnNEg9wzFzzHlEbHGSV/Sl7YMnxkh/6nLH6zUIHpAa0M2WgtGfr1yrM6B3z5btVm9beaoQHZBDvry1gZvM+lYUN6Qv1GlA74UtZzDOxhmzjD3p/HvrLRuRNyGMdAd6Hzrt8ReXiGuO7a09eJ3j28Aqj2LiEG+bS/dgiXSbTLdlOLfI=
