  import { DA_TYPE } from './da-type';
  import {DA_REQUIREMENT_TASK_LIST} from './da-taskList';
  import { DA_UPLOAD } from './da-uploadOverview';
  import {
    DA_GET_UPLOAD_ATTACHMENT,
    DA_POST_UPLOAD_ATTACHMENT,
    DA_POST_UPLOAD_ATTACHMENT_PROCEED,DA_GET_REMOVE_FILES_ATTACHMENT
  } from './da-uploadAttachment';
  import { DA_GET_UPLOAD_DOC, DA_POST_UPLOAD_DOC, DA_GET_REMOVE_FILES, DA_POST_UPLOAD_PROCEED } from './da-upload';
  import { DA_GET_UPLOAD_ADDITIONAL , DA_POST_UPLOAD_ADDITIONAL,DA_POST_UPLOAD_ADDITIONAL_PROCEED } from './da-uploadAdditional';
  import { DA_GET_I35, DA_POST_I35 } from './da-Ir35';
  import {DA_GET_NAME_PROJECT,DA_POST_NAME_PROJECT} from './da-nameAProject';
  import {DA_GET_LEAD_PROCUREMENT,DA_PUT_LEAD_PROCUREMENT,DA_GET_USER_PROCUREMENT} from './da-leadProcurement';
  import { DA_GET_YOUR_ASSESSTMENT } from './da-yourassesstment';
  import { DA_Assesstment_GET_QUESTIONS,DA_Assesstment_POST_QUESTION } from './da-questions-yourassesstment';

  import { DA_GET_ADD_COLLABORATOR,DA_POST_ADD_COLLABORATOR,DA_POST_ADD_COLLABORATOR_JSENABLED,DA_POST_ADD_COLLABORATOR_TO_JAGGER,DA_POST_PROCEED_COLLABORATORS,DA_POST_DELETE_COLLABORATOR_TO_JAGGER } from './da-addcollaborator';
  import { DA_GET_SELECTED_SERVICE,DA_POST_SELECTED_SERVICE } from './da-selectedService';
  import { DA_ADD_CONTEXT } from './da-addcontext';
  import { SUPPLIER_DA_RATECARD } from './da-supplierRateCard';
  
  import { GET_DA_SUPPLIERS,POST_DA_SUPPLIER } from './da-suppliers';
  import { DA_GET_EVENT_PUBLISHED } from './da-eventpublished';
  import { DA_GET_QUESTIONS,DA_POST_QUESTIONS } from './da-questions';
  import { GET_DA_REVIEW,POST_DA_REVIEW } from './da-review';
  import { DA_GET_RESPONSE_DATE, DA_POST_ADD_RESPONSE_DATE, DA_POST_RESPONSE_DATE } from './da-responsedate';

  /**
   * @BaseController
   * @Provider
   *
   * @description Provides as Base for all Controllerw
   */
  export const REQUIREMENT_CONTROLLER = {
    DA_TYPE,
    DA_REQUIREMENT_TASK_LIST,
    DA_UPLOAD,
    DA_GET_UPLOAD_ATTACHMENT,
    DA_POST_UPLOAD_ATTACHMENT,
    DA_POST_UPLOAD_ATTACHMENT_PROCEED,
    DA_GET_UPLOAD_DOC,
    DA_POST_UPLOAD_DOC,
    DA_GET_REMOVE_FILES,
    DA_POST_UPLOAD_PROCEED,
    DA_POST_UPLOAD_ADDITIONAL_PROCEED,
    DA_GET_UPLOAD_ADDITIONAL,
    DA_POST_UPLOAD_ADDITIONAL,
    DA_GET_REMOVE_FILES_ATTACHMENT,
    DA_GET_I35,
    DA_POST_I35,
    DA_GET_ADD_COLLABORATOR,
    DA_GET_SELECTED_SERVICE,
    DA_POST_SELECTED_SERVICE,
    DA_POST_ADD_COLLABORATOR,
    DA_POST_ADD_COLLABORATOR_JSENABLED,
    DA_POST_ADD_COLLABORATOR_TO_JAGGER,
    DA_POST_PROCEED_COLLABORATORS,
    DA_POST_DELETE_COLLABORATOR_TO_JAGGER,
    DA_ADD_CONTEXT,
    GET_DA_SUPPLIERS,
    POST_DA_SUPPLIER,
    DA_GET_EVENT_PUBLISHED,
    DA_GET_QUESTIONS,
    DA_POST_QUESTIONS,
    GET_DA_REVIEW,
    POST_DA_REVIEW,
    DA_GET_NAME_PROJECT,
    DA_POST_NAME_PROJECT,
    DA_GET_LEAD_PROCUREMENT,
    DA_PUT_LEAD_PROCUREMENT,
    DA_GET_USER_PROCUREMENT,
    DA_GET_YOUR_ASSESSTMENT,
    //BALWINDER START
    DA_Assesstment_GET_QUESTIONS,
    DA_Assesstment_POST_QUESTION,
   //Response Date
   DA_GET_RESPONSE_DATE,
   DA_POST_RESPONSE_DATE,
   DA_POST_ADD_RESPONSE_DATE,
   SUPPLIER_DA_RATECARD,
  };