import {
  GET_OPPORTUNITIES,
  GET_OPPORTUNITIES_DETAILS,
  GET_OPPORTUNITIES_API,
  GET_OPPORTUNITIES_DETAILS_REVIE_RECOMMENDATION,
  GET_OPPORTUNITIES_QA,
} from './opportunities';

export const DIGITALOUTCOMES_CONTROLLER = {
  /**
   * @GET_VIEW
   */
  GET_OPPORTUNITIES,
  GET_OPPORTUNITIES_DETAILS,
  GET_OPPORTUNITIES_API,
  GET_OPPORTUNITIES_DETAILS_REVIE_RECOMMENDATION,
  GET_OPPORTUNITIES_QA,
  /**
   * @POST_VIEW
   */
  // POST_FILTER,
};
