import { GET_OPPORTUNITIES, GET_OPPORTUNITIES_DETAILS, GET_OPPORTUNITIES_API } from './opportunities';

export const DIGITALOUTCOMES_CONTROLLER = {
  /**
   * @GET_VIEW
   */
  GET_OPPORTUNITIES,
  GET_OPPORTUNITIES_DETAILS,
  GET_OPPORTUNITIES_API,
  /**
   * @POST_VIEW
   */
  // POST_FILTER,
};
