export enum logConstant {
    //@ All of the log message content related
    loginSuccess = 'Login successfully',
    logoutSuccess = 'Logout successfully',
    dashLandLog = 'Dashboard page reached',
    chooseCommercialLandLog = 'Choose a commercial agreement page reached',
    aggrementDetailFetch = 'Feached agreement details from Agreement service API',
    lotDetailsFromAggrement = 'Feached Lot details from Agreement service API',
    collaboratorDetailFetch = 'Feached collaborator details from Organization service API',
    userDetailFetch = 'Feached user details from Tender API',
    collaboratorSave = 'Saved collaborator from Tender API',
    collaboratorDelete = 'Delete collaborator from Tender API',
    evenTypeFromAggrementLot = 'Feached event types from specific Agreement lot service API',
    procurementCreated = 'Procurement created',
    procurementPage = 'Procurement page reached',
    postSaveEventsToProject = 'Selected events update to the project',
    exportDetailFetch = 'Download project details from Tender API',
    questionsFetch = 'Feached criterian group questions details from Tender API',
    documentsFetch = 'Feached Ir35 documents from Tender API',
    documentsSave = 'Saved Ir35 documents from Tender API',
    saveLeadProcurement = 'Saved Lead Procurement from Tender API',
    fetchEventDetails = 'Fetched event details from project',
    fetchAssesmentDetails = 'Fetched assessment details',
    fetchAssesmentDimentionDetails = 'Fetched assessment dimensions details',
    writePublishPage = 'Write and publish your requirements reached',
    criteriaDetailFetch =' Feached criteria details from Tender API',
    fetchedAssesstmentsQuestions = 'Feached Assesstments Questions from Tender API',
    yourassesstments = 'Your Assesstments page reached',
    saveassesstments = 'Saved Assesstments from Tender API',
    fetchedQuestions = 'Feached Questions from Tender API',
    savequestions = 'Saved Questions from Tender API',
    keyDates = 'Feached Dates from Tender API',
    addContectRequirementPage ='Add context and requirements reached',
    questionDetail ='Question detail',
    questionGroupDetail ='Question group detail',
    questionPage ='Question page reached',
    questionUpdated ='Question updated',
    ResponseDateLog = 'Response Date page reached',
    saveKeyDates = 'Saved Response Date from Tender API',
    ReviewLog = 'Review page reached',
    ReviewSave = 'Published the project from Tender API',
    fetchEvents = 'Feached Events from Tender API',
    fetchSupplierScoreList = 'Feached Supplier Score List from Tender API',
    selectedService = 'Service page reached',
    saveAssesmentDetails = 'Saved assesment from Tender API',
    savesupplier = 'Saved supplier from Tender API',
    supplierRateCard='Supplier Rate Card page reached',

    
   

    rfichangeLeadProcurementPageLog='Change who will lead the procurement page reached',
    rfigetUserDetails="Get logged user detail",
    rfigetUserOrgProfile ="Get logged user organisation profiles detail",
    rfichangeLeadProcurementUpdate = 'Change who will lead the procurement Updated',
    rfiaddColleaguesPageLog = 'Add colleagues to your project reached',
    rfiaddColleaguesUpdated = 'Add colleagues to your project reached Updated',



    NameAProjectLog = 'Name your project page reached',
    NameAProjectUpdated = 'Name your project updated',


    getUserDetails = 'Get logged user detail',
    getUserOrgProfile = 'Get logged user organisation profiles detail',
    changeLeadProcurementPage = 'Change who will lead the procurement reached',
    changeLeadProcurementUpdate = 'Change who will lead the procurement Updated',
    addColleaguesPage = 'Add colleagues to your project reached',
    addColleaguesUpdated = 'Add colleagues to your project reached Updated',
    chooseHowBuildYourRfiPageLog = 'Choose how to build your RfI page reached',
    chooseHowBuildYourRfiUpdated = 'Choose how to build your RfI Updated',
    buildYourRfiPageLog = 'build your RfI page reached',
    buildYourRfiQuestionList= 'Fetched Rfi Questions',
    rfiQuestionPageLog= 'Rfi Question page reached',
    rfiQuestionDetails= 'Fetched Rfi Question details',
    rfiQuestionUpdated="Question updated",
    rfiUploadDocumentPageLog="Upload documents page reached",
    rfigetUploadDocument="Fetched Upload documents",
    rfiUploadDocumentUpdated="New document uploaded",
    rfiViewSuppliersPageLog="View suppliers page reached",
    supplierList="Fetched supplier list",
    setYourTimeLinePageLog="Set your RfI timeline page reached",
    yourTimeLineUpdate="Rfi Tmeline updated",
    reviewAndPublishPageLog="Review and publish your RFI page reached",
    rfiEventDetails="Fetched the event details",
    rfiPublishLog="Your RfI has been published",
    rfiPublishPageLog="Rfi published page reached",
    
}