#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    host: ccs-scale-cat-buyer-ui.london.cloudapps.digital
    path: /lucky/number
    controller: App\Controller\LuckyController::number