/* tslint:disable */
/* eslint-disable */
/**
 * SCALE Commercial Agreements Service
 * This API allows access to CCS Commercial Agreement data. This is used both to provide information to users and to govern the behaviour of other systems for example 'Buy a Thing' and 'Contract for a Thing', where processes may differ based on the configuration of the underlying Commercial Agreement and Lot.
 *
 * OpenAPI spec version: v0.0.9
 * Contact: apiteam@crowncommercial.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LotSupplier
 */
export interface LotSupplier {
    /**
     * 
     * @type {Organization}
     * @memberof LotSupplier
     */
    organization?: any;
    /**
     * 
     * @type {string}
     * @memberof LotSupplier
     */
    supplierStatus?: LotSupplierSupplierStatusEnum;
    /**
     * 
     * @type {Array&lt;Contact&gt;}
     * @memberof LotSupplier
     */
    lotContacts?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum LotSupplierSupplierStatusEnum {
    Active = 'active',
    Suspended = 'suspended',
    Excluded = 'excluded'
}

