/* tslint:disable */
/* eslint-disable */
/**
 * SCALE Commercial Agreements Service
 * This API allows access to CCS Commercial Agreement data. This is used both to provide information to users and to govern the behaviour of other systems for example 'Buy a Thing' and 'Contract for a Thing', where processes may differ based on the configuration of the underlying Commercial Agreement and Lot.
 *
 * OpenAPI spec version: v0.0.9
 * Contact: apiteam@crowncommercial.gov.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LotDetail
 */
export interface LotDetail {
    /**
     * 
     * @type {LotId}
     * @memberof LotDetail
     */
    number?: any;
    /**
     * Lot name
     * @type {string}
     * @memberof LotDetail
     */
    name?: any;
    /**
     * Effective start date of Lot
     * @type {string}
     * @memberof LotDetail
     */
    startDate?: any;
    /**
     * Effective end date of Lot
     * @type {string}
     * @memberof LotDetail
     */
    endDate?: any;
    /**
     * Short textual description of the Lot
     * @type {string}
     * @memberof LotDetail
     */
    description?: any;
    /**
     * Supplier count
     * @type {string}
     * @memberof LotDetail
     */
    suppliers?: any;
    /**
     * 
     * @type {string}
     * @memberof LotDetail
     */
    type?: LotDetailTypeEnum;
    /**
     * Routes to Market for the Lot and associated bounds
     * @type {Array&lt;RouteToMarket&gt;}
     * @memberof LotDetail
     */
    routesToMarket?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof LotDetail
     */
    sectors?: any;
    /**
     * 
     * @type {Array&lt;RelatedAgreementLot&gt;}
     * @memberof LotDetail
     */
    relatedAgreementLots?: any;
    /**
     * 
     * @type {Array&lt;LotRule&gt;}
     * @memberof LotDetail
     */
    rules?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum LotDetailTypeEnum {
    Product = 'product',
    Service = 'service',
    ProductAndService = 'product and service'
}

