import { REQUIREMENT_CHOOSE_ROUTE, POST_REQUIREMENT_CHOOSE_ROUTE } from './choose-route';
import { REQUIREMENT_RFP_TYPE, POST_RFP_TYPE } from './rfp-type';
import { REQUIREMENT_RFP_TASK_LIST } from './rfp-taskList';
import {
  GET_ADD_COLLABORATOR,
  POST_ADD_COLLABORATOR_JSENABLED,
  POST_ADD_COLLABORATOR,
  POST_ADD_COLLABORATOR_TO_JAGGER,
  POST_PROCEED_COLLABORATORS,
} from './addcollaborator';
import { GET_LEAD_PROCUREMENT, PUT_LEAD_PROCUREMENT, GET_USER_PROCUREMENT } from './leadProcurement';
import { GET_NAME_PROJECT, POST_NAME_PROJECT } from './nameAProject';
import { OFFLINE_JOURNEY_PAGE } from './offline';
import { GET_CA_TASK_LIST } from './ca-taskList';
import { GET_UPLOAD_DOC, POST_UPLOAD_DOC, GET_REMOVE_FILES, POST_UPLOAD_PROCEED } from './upload';
import { GET_CA_LEARN, POST_CA_LEARN } from './ca-learnAboutCapabilityAssessment';
import { GET_CA_WEIGHTINGS } from './ca-enterYourWeightings';
/**
 * @BaseController
 * @Provider
 *
 * @description Provides as Base for all Controller
 */
export const REQUIREMENT_CONTROLLER = {
  REQUIREMENT_CHOOSE_ROUTE,
  REQUIREMENT_RFP_TYPE,
  POST_REQUIREMENT_CHOOSE_ROUTE,
  POST_RFP_TYPE,
  REQUIREMENT_RFP_TASK_LIST,
  GET_ADD_COLLABORATOR,
  POST_ADD_COLLABORATOR_JSENABLED,
  POST_ADD_COLLABORATOR,
  POST_ADD_COLLABORATOR_TO_JAGGER,
  POST_PROCEED_COLLABORATORS,
  GET_NAME_PROJECT,
  POST_NAME_PROJECT,
  GET_LEAD_PROCUREMENT,
  PUT_LEAD_PROCUREMENT,
  GET_USER_PROCUREMENT,
  OFFLINE_JOURNEY_PAGE,
  GET_CA_TASK_LIST,
  GET_UPLOAD_DOC,
  POST_UPLOAD_DOC,
  GET_REMOVE_FILES,
  POST_UPLOAD_PROCEED,
  GET_CA_LEARN,
  POST_CA_LEARN,
  GET_CA_WEIGHTINGS,
};
